POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "email": "tuladharsamyak@gmail.com",
    "password": "password"
}

###
GET http://localhost:4000/api/v1/authors
Content-Type: application/json
X-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXIiOnsiaWQiOjEsIm5hbWUiOiJuaWNrIiwiZW1haWwiOiJ0dWxhZGhhcnNhbXlha0BnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkQXQiOm51bGwsInBhc3N3b3JkIjoiJDJhJDEwJGRncll2Y2RXQnJPbTRrSUM4bmdsNnVERG9wbDFiUDJ4UTRPMTZ1V2VQc295UWRIOEJJVTlpIiwidXNlclR5cGUiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiIsInVwZGF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiJ9fSwiaWF0IjoxNjQ4NDM0NDk0LCJleHAiOjE2NDg0NzA0OTR9.4abTvTNPeLYnC4hrXcwI1Od89WUs6g4YGaDeSe_0N9g

###
GET http://localhost:4000/api/v1/authors/1/books
Content-Type: application/json
X-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXIiOnsiaWQiOjEsIm5hbWUiOiJuaWNrIiwiZW1haWwiOiJ0dWxhZGhhcnNhbXlha0BnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkQXQiOm51bGwsInBhc3N3b3JkIjoiJDJhJDEwJGRncll2Y2RXQnJPbTRrSUM4bmdsNnVERG9wbDFiUDJ4UTRPMTZ1V2VQc295UWRIOEJJVTlpIiwidXNlclR5cGUiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiIsInVwZGF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiJ9fSwiaWF0IjoxNjQ5MTI1NTYzLCJleHAiOjE2NDkxNjE1NjN9.78b5RAodpxxeYwn5Gbx2QfQeqe9krWZfx37OaLAtBNw

###
POST http://localhost:4000/api/v1/authors/1/books
Content-Type: application/json
X-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXIiOnsiaWQiOjEsIm5hbWUiOiJuaWNrIiwiZW1haWwiOiJ0dWxhZGhhcnNhbXlha0BnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkQXQiOm51bGwsInBhc3N3b3JkIjoiJDJhJDEwJGRncll2Y2RXQnJPbTRrSUM4bmdsNnVERG9wbDFiUDJ4UTRPMTZ1V2VQc295UWRIOEJJVTlpIiwidXNlclR5cGUiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiIsInVwZGF0ZWRBdCI6IjIwMjItMDMtMjRUMTE6NDI6MjQuMDQyWiJ9fSwiaWF0IjoxNjQ4NzA0OTAyLCJleHAiOjE2NDg3NDA5MDJ9.NhhDi3BHhmYpr8kgRmoiLRl7OgpkyFERUzrmjoqdBsA

{
    "name": "laravel",
    "isbn": "132465",
    "price":"12.69",
    "addedBy": 1
}